### ISSUE TITLE
Read More Link

### ISSUE THREAD

**Issue by JosChavz** [mxttwoods/allyearheating#30]
In the page [About](https://allyearheating.com/about/), there is a link that takes you to google with a populated search. 
However, what was the point of doing so? Clicking it just made the customer go outside the website. 

I think if it was meant for a Yelp page then perhaps link that but make a new window instead.

**Comment by mxttwoods** [comment]
Thanks for the thoughtful message, normally I would use a embedded viewer. But this is a requirement from the business and is outside my scope as the Developer.  

Matthew Woods

**Comment by mxttwoods** [comment]
Reopening and proposing hotfix to the owner.

Thanks for the help, @JosChavz

**Comment by mxttwoods** [comment]
Fixed in Release 1.3.8
